name: acadease
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dropdown_button2: ^2.3.9
  google_fonts: ^6.1.0
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  flutter_bounce: ^1.1.0
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.4
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  provider: ^6.1.1
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
    
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    
